### ISSUE TITLE
ja_jp spell miss

### ISSUE THREAD

**Issue by Wokashi0801** [0999312/umapyoi#21]
![C__Users_shu08_AppData_Local_Temp_Temp1a5392d8-0f03-4dd5-b8bc-69a874bf8c64_umapyoi-1 0 18-1 18 2 zip_assets_umapyoi_lang_ja_jp json - Sublime Text (UNREGISTERED) 2023_09_08 16_28_49](https://github.com/0999312/umapyoi/assets/128286414/b316adb5-5e28-4661-876b-d9fe176c460b)
Game version: 1.18.2
Mod version: umapyoi 1.0.18

**Comment by 0999312** [comment]
Well, Don't be bothered with these small details ;)
The problem has been discovered before, but if the final result is okay, it is better not to change it yet.
Otherwise, update compatibility may be affected to a certain extent.
It would be more appropriate to fix these details in the next major minecraft version update.
